---

- name: Create non-root user
  user: >
    name="{{ ssh_user }}"
    comment="Admin user"
    state=present
    groups="{{ ssh_groups }}"
    shell=/bin/bash
    append=yes
    createhome=yes

- name: Deploy ssh public key
  authorized_key: user="{{ ssh_user }}" key="{{ ssh_pub_key }}"
